/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAdminUploadPdfRouteImport } from './routes/api/admin/upload-pdf'
import { Route as ApiAdminStatusRouteImport } from './routes/api/admin/status'
import { Route as ApiAdminCrawlRouteImport } from './routes/api/admin/crawl'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadPdfRoute = ApiAdminUploadPdfRouteImport.update({
  id: '/api/admin/upload-pdf',
  path: '/api/admin/upload-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatusRoute = ApiAdminStatusRouteImport.update({
  id: '/api/admin/status',
  path: '/api/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCrawlRoute = ApiAdminCrawlRouteImport.update({
  id: '/api/admin/crawl',
  path: '/api/admin/crawl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/upload-pdf': typeof ApiAdminUploadPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/upload-pdf': typeof ApiAdminUploadPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/admin/crawl': typeof ApiAdminCrawlRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/upload-pdf': typeof ApiAdminUploadPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/admin/crawl'
    | '/api/admin/status'
    | '/api/admin/upload-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat'
    | '/api/admin/crawl'
    | '/api/admin/status'
    | '/api/admin/upload-pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/admin/crawl'
    | '/api/admin/status'
    | '/api/admin/upload-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiAdminCrawlRoute: typeof ApiAdminCrawlRoute
  ApiAdminStatusRoute: typeof ApiAdminStatusRoute
  ApiAdminUploadPdfRoute: typeof ApiAdminUploadPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-pdf': {
      id: '/api/admin/upload-pdf'
      path: '/api/admin/upload-pdf'
      fullPath: '/api/admin/upload-pdf'
      preLoaderRoute: typeof ApiAdminUploadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/status': {
      id: '/api/admin/status'
      path: '/api/admin/status'
      fullPath: '/api/admin/status'
      preLoaderRoute: typeof ApiAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/crawl': {
      id: '/api/admin/crawl'
      path: '/api/admin/crawl'
      fullPath: '/api/admin/crawl'
      preLoaderRoute: typeof ApiAdminCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiAdminCrawlRoute: ApiAdminCrawlRoute,
  ApiAdminStatusRoute: ApiAdminStatusRoute,
  ApiAdminUploadPdfRoute: ApiAdminUploadPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
